main/posts/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  content = TextAreaField('Content', validators=[DataRequired()])
  submit = SubmitField('Post')

main/main/routes.py
from flask import Blueprint, render_template, request
from main.models import Post
import predict

main = Blueprint('main', __name__)

thumbnails = [
  {
    'author': 'Ali',
    'title': 'Computer Scripting',
    'content': 'Computer Scripting',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
  },
  {
    'author': 'Joey',
    'title': 'Cooling On The Beach',
    'content': 'Second post',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1541739900389-5f066a7d8c99?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=600'
  },
  {
    'author': 'Vinchhi',
    'title': 'Having A Fun Adventure',
    'content': 'Second post',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1550424616-3d37bc3e9a2a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
  },
  {
    'author': 'Vinchhi',
    'title': 'Getting Ready For Spring',
    'content': 'Second post',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1567226055219-bd1ee70f3d5c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
  },
  {
    'author': 'Ali',
    'title': 'Testing Out The New Whip',
    'content': 'Second post',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1566790050901-772dc40a79f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
  },
  {
    'author': 'Billy',
    'title': 'Having Fun In Nature',
    'content': 'Second post',
    'date_posted': 'June 4 2020',
    'image': 'https://images.unsplash.com/photo-1567127214373-7ca7b33baf25?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
  }
]








@main.route('/', methods=['GET', 'POST'])
def home():
  if request.method == 'POST':
    youtube_url = str(predict.predict(request.form['url']))

    return render_template("index.html", youtube_url=youtube_url)
  
  else:
    return render_template("index.html")

@main.route('/advice')
def advice():
  return render_template("advice.html")

@main.route('/posts')
def images():
  page = request.args.get('page', 1, type=int)
  posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
  return render_template("instagram.html", posts=posts)

@main.route('/gallery')
def gallery():
  return render_template("gallery.html", thumbnails=thumbnails)

main/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required 
from main import db
from main.models import Post 
from main.posts.forms import PostForm

posts = Blueprint('posts', __name__)



@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
  form = PostForm()
  if form.validate_on_submit():
    post = Post(title=form.title.data, content=form.content.data, author=current_user)
    db.session.add(post)
    db.session.commit()
    flash('Your post has been created!', 'success')
    return redirect(url_for("main.images"))
  return render_template("create_post.html", form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template("post.html", post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403)
  form = PostForm()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Your post has been updated!', 'success')
    return redirect(url_for('posts.post', post_id=post.id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('create_post.html', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Your post has been deleted!', 'success')
  return redirect(url_for("main.images"))

main/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main import db, bcrypt
from main.models import User, Post
from main.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from main.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash('Account created. You can now log in!', 'success')
    return redirect(url_for("users.login"))
  return render_template("register.html", form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash('Login Unsuccessful, please check email and password', 'danger')

  return render_template("login.html", form=form)

@users.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('main.home'))



@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateAccountForm()

  if form.validate_on_submit():
    if form.picture.data:
      picture_file = save_picture(form.picture.data)
      current_user.image_file = picture_file

    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account has been updated!', 'success')
    return redirect(url_for('users.account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
    
  image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
  return render_template("account.html", image_file=image_file, form=form)





@users.route('/user/<string:username>')
def user_posts(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  posts = Post.query.filter_by(author=user)\
    .order_by(Post.date_posted.desc())\
    .paginate(page=page, per_page=5)
  return render_template("user_posts.html", posts=posts, user=user)




@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    send_reset_email(user)
    flash('An email has been sent with instructions to reset your password', 'info')
    return redirect(url_for('users.login'))
  return render_template('reset_request.html', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  user = User.verify_reset_token(token)
  if user is None:
    flash('That is an invalid or expired token', 'warning')
    return redirect(url_for('users.reset_request'))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user.password = hashed_password
    db.session.commit()
    flash('Your password has been updated! You can now login', 'success')
    return redirect(url_for("users.login"))
  return render_template('reset_token.html', form=form)

main/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="content-section" style="width: 800px;">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Account Info</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
        {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.picture.label() }}
        {{ form.picture(class="form-control-file") }}
        {% if form.picture.errors %}
        {% for error in form.picture.errors %}
        <span class="text-danger">{{ error }}</span></br>
        {% endfor %}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

main/templates/advice.html
{% extends "base.html" %}
{% set active_page = "advice" %}
{% block content %}
<article class="container card" style="padding: 30px;" id="contentmargin">
  <h1>How to Go Viral</h1>
  <p>
    <a class="link" href="https://www.businessinsider.com/american-kids-youtube-star-astronauts-survey-2019-7" target="_blank" rel="noopener noreferrer">A recent survey</a> showed that the most popular career American children want to have is — not astronaut, not teacher, not even president — but a <b>Youtuber</b>. It’s every kid’s dream to go viral on YouTube and have <i>millions</i> of people view your content.  But often it feels like no matter how many hours you put into your video, both your views and your popularity will fail to grow. With this introduction, you will know the steps you should take to make your channel grow and rake into those subscribers!
  </p>
  <p>
    The most important things to do when trying to go viral is:
  </p>
  <!-- list -->
  <ul class="fa-ul">
    <li>
      <span class="fa-li"><i class="far fa-check-circle"></i></span> Know your Audience
    </li>
    <li>
      <span class="fa-li"><i class="far fa-check-circle"></i></span> Look Interesting
    </li>
    <li>
      <span class="fa-li"><i class="far fa-check-circle"></i></span>
      Be Engaging
    </li>
    <li>
      <span class="fa-li"><i class="far fa-check-circle"></i></span>
      Network with Others
    </li>
  </ul>
  <!-- Article -->
  <!-- Heading 1 -->
  <h3 class="viralHeading">1. Know your Audience </h3>
  <p>
    Look out for the hottest trends. There are <i>countless people</i> on YouTube searching for their favorite content creator, and you have to do what it takes to know them in. Spend your time viewing your own content and niches and explore the depths of YouTube. One way to know what's trending is to look at <a class="link" href="https://trends.google.com/" target="_blank" rel="noopener noreferrer">Google Trends</a>, which shows the statistics of what’s being searched on Google right now. Once you've figured out something trendy, adapt to it. Know what’s trending and try to integrate it into your work, and take into account what your audience wants to see!
  </p>
  <!-- Heading 2 -->
  <h3 class="viralHeading">2. Look Interesting </h3>
  <p>
    You want to grab the attention of potential viewers. What is the first thing a person will do when searching for their favorite topic? I'll give you a hint, they'll look at your thumbnail, profile picture, and title. Don't just add a random thumbnail, be sure to personalize it! Be sure to also make your title relevant with a slight sense of clickbait. Do whatever it takes so that in one glance, any prospective subscriber will see your content and think “hey, today I’m going to click that.”
  </p>
  <!-- Heading 3 -->
  <h3 class="viralHeading">3. Be Engaging </h3>
  <p>
    Once you start reeling people in with those beautiful thumbnails and pictures, make good content. Yes, it’s that simple. You got them into your doorstep, now impress them with your impressive editing, incredible footage, and the best video you can muster. Spend time, effort, and imagination on your videos. Be creative, think out of the box, and in no time, you’ll be getting your likes, comments, and subscribers.
  </p>
  <h3 class="viralHeading">4. Network with Others </h3>
  <p>
    This is one of the most undervalued aspects of growing your channel. Being a small fish in a big pond is no doubt going to be difficult, so it’s best to do it with friends! You want to network with others, such as content creators, so you can collaborate and grow your channel together. You’ll both be able to bounce ideas, create much more entertaining videos, and share audiences. At the end of the day, both of you will grow as YouTubers. The more that people hear about your channel, the more potential views you are able to get!
  </p>
</article>
{% endblock %}

main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- note: ctrl+shift+r to refresh since repl.it caches css-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://kit.fontawesome.com/a5d65ee1b1.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>ViralCheck</title>
  </head>
  <header class="site-header">
    <nav class="navbar navbar-expand-xl navbar-light bg-white fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">
        <img src="{{ url_for('static', filename='viralcheck.svg') }}" width="30" height="30" class="d-inline-block align-top" alt=""> 
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link {{ 'active' if active_page == 'home' else '' }}" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i>  Home</a>
            <a class="nav-item nav-link {{ 'active' if active_page == 'advice' else '' }}" href="{{ url_for('main.advice') }}"><i class="fas fa-trophy"></i>  Advice</a>
            <a class="nav-item nav-link {{ 'active' if active_page == 'images' else '' }}" href="{{ url_for('main.images') }}"><i class="fas fa-comments"></i>  Forums</a>
            <a class="nav-item nav-link {{ 'active' if active_page == 'gallery' else '' }}" href="{{ url_for('main.gallery') }}"><i class="fas fa-images"></i>  Gallery</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="btn btn-outline-success" href="{{ url_for('posts.new_post') }}" style="margin-right: 16px;">New Post</a>
            <a class="btn btn-outline-success" href="{{ url_for('users.account') }}" style="margin-right: 16px;">Account</a>
            <a class="btn btn-outline-success" href="{{ url_for('users.logout') }}" style="margin-right: 16px;">Logout</a> {% else %}
            <a class="btn btn-outline-success" href="{{ url_for('users.login') }}" style="margin-right: 16px;">Login</a>
            <a class="btn btn-success" href="{{ url_for('users.register') }}">Register</a> {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <!-- Flash Messages -->
    <div class="container" id="contentmargin" style="{{ 'display: none;' if active_page == 'home' else '' }}">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %}
    </div>
  </header>
  <div>
  {% block content %} {% endblock %}
  <!-- Footer Stuff -->
  <footer style="{{ 'display: none;' if active_page == 'home' else '' }}">
    Made with ❤️ for
    <a href="https://organize.mlh.io/participants/events/3480-notuniversity-hacks" target="_blank" rel="noopener noreferrer"> NotUniversity Hacks</a> | See code <a href="https://github.com/aahmad4/ViralCheck-YouTube-Algorithm-Predictor" target="_blank" rel="noopener noreferrer"> here </a>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="content-section" style="width: 800px;">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
        {{ form.title(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
        {{ form.content(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

main/templates/gallery.html
{% extends "base.html" %}
{% set active_page = "gallery" %}
{% block content %}
<div class="container card" id="contentmargin" style="padding: 30px;">
  <h1>Gallery of Thumbnail Ideas</h1>
  <br>
  <div class="row text-center" style="display: flex; flex-wrap: wrap;">
    {% for thumbnail in thumbnails %}
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card" style="width: 100%; opacity: 1; transition: 0.35; padding: 0; margin-bottom: 20px">
        <img src="{{thumbnail.image}}" class="card-img-top" style="">
        <div class="card-body">
          <h5 class="card-title">{{ thumbnail.title }}</h5>
          <p class="card-text">By {{ thumbnail.author }} on {{ thumbnail.date_posted }}</p>
          <!-- <a href="#" class="btn btn-outline-success">View</a> -->
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

main/templates/instagram.html
{% extends "base.html" %}
{% set active_page = "images" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section" style="width: 800px;">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div style="display: flex; align-items: center; justify-content: center; ">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" style="margin-right: 0.7rem;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    </div>
{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% set active_page = "login" %}
{% block content %}
<div class="container" id="" >
  <div class="content-section" style="width: 800px;">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Login</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span> {% endfor %}
          </div>
          {% else %} {{ form.email(class="form-control form-control-lg") }} {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }} {% if form.password.errors %} {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span> {% endfor %}
          </div>
          {% else %} {{ form.password(class="form-control form-control-lg") }} {% endif %}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
        <small class="text-muted">
        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
      </small>
      </div>
    </form>
    <div class="border-top pt-1">
    <small class="text-muted">
    Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
  </div>
  </div>
</div>
{% endblock %}

main/templates/post.html
{% extends "base.html" %}
{% block content %}
<div id="contentmargin">
  <article class="media content-section" style="width: 800px;">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
        <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
    <h1 class="mb-3 text-center">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section" style="width: 800px;">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div style="display: flex; align-items: center; justify-content: center; ">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    </div>
{% endblock content %}